version: '3'

services:
  wp:
    image: wordpress:latest 
    restart: always
    ports:
      - 8080:80 
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
      - ./wp-themes:/var/www/html/wp-content/themes
      - ./wp-plugins:/var/www/html/wp-content/plugins    
      - ./wp-uploads:/var/www/html/wp-content/uploads   
      #- ./config/preload.php:/var/www/html/preload.php
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA: |
        /* begin wordpress condig extra */

        /* AWS Cloudfront */      
        if (isset($_SERVER['HTTP_CLOUDFRONT_FORWARDED_PROTO']) && $_SERVER['HTTP_CLOUDFRONT_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }      

        /* Multisite */
        define( 'WP_ALLOW_MULTISITE', true );
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', getenv("DOMAIN_CURRENT_SITE") );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 );   

        define( 'WP_CACHE', getenv("WP_CACHE") );
        define( 'WP_SITEURL', 'https://' . $$_SERVER['HTTP_HOST'] );
        define( 'WP_HOME', 'https://' . $$_SERVER['HTTP_HOST'] );

        /* SES */
        define( 'WPOSES_AWS_ACCESS_KEY_ID', getenv("WPOSES_AWS_ACCESS_KEY_ID") );
        define( 'WPOSES_AWS_SECRET_ACCESS_KEY', getenv("WPOSES_AWS_SECRET_ACCESS_KEY") );

        /* end wordpress condig extra */
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    user: "33:33"
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
      - ./wp-themes:/var/www/html/wp-content/themes
      - ./wp-plugins:/var/www/html/wp-content/plugins
      - ./wp-uploads:/var/www/html/wp-content/uploads
    env_file:
      - .env
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8088:80
    depends_on:
      - db    
    links:
      - db:db

  db:
    image: mysql:latest 
    ports:
      - ${IP}:3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data:
  wp-app:        
