version: '3.2'

services:
  wpconfig:
    image: wordpress:latest 
    restart: "no"
    ports:
      - 18880:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-themes:/var/www/html/wp-content/themes
      - ./wp-plugins:/var/www/html/wp-content/plugins    
      - ./wp-uploads:/var/www/html/wp-content/uploads   
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA: |
        /* begin wordpress config extra */

        /* AWS Cloudfront */      
        if (null !== $$_SERVER['HTTP_CLOUDFRONT_FORWARDED_PROTO'] && $$_SERVER['HTTP_CLOUDFRONT_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }      

        /* Multisite */
        if (getenv("MULTISITE")) {
           define( 'WP_ALLOW_MULTISITE', true );
           define( 'MULTISITE', true );
           define( 'SUBDOMAIN_INSTALL', false );
           define( 'DOMAIN_CURRENT_SITE', getenv("DOMAIN_CURRENT_SITE") );
           define( 'PATH_CURRENT_SITE', '/' );
           define( 'SITE_ID_CURRENT_SITE', 1 );
           define( 'BLOG_ID_CURRENT_SITE', 1 );   
        }

        define( 'FORCE_SSL_ADMIN', true );

        define( 'WP_CACHE', getenv("WP_CACHE") );
        define( 'WP_SITEURL', 'https://' . $$_SERVER['HTTP_HOST'] );
        define( 'WP_HOME', 'https://' . $$_SERVER['HTTP_HOST'] );

        /* SES */
        define( 'WPOSES_AWS_ACCESS_KEY_ID', getenv("WPOSES_AWS_ACCESS_KEY_ID") );
        define( 'WPOSES_AWS_SECRET_ACCESS_KEY', getenv("WPOSES_AWS_SECRET_ACCESS_KEY") );

        /* end wordpress condig extra */
    depends_on:
      - db
    links:
      - db
    #command: echo "wp-config.php created."

  db:
    image: mysql:latest 
    ports:
      - ${IP}:3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    cap_add:
      - SYS_NICE
      
  wpcli:
    restart: "no"
    image: wordpress:cli
    user: "0:0"
    volumes:
      - wp-data:/var/www/html
      - ./wp-themes:/var/www/html/wp-content/themes
      - ./wp-plugins:/var/www/html/wp-content/plugins
      - ./wp-uploads:/var/www/html/wp-content/uploads
    env_file:
      - .env
    depends_on:
      - db
      - wpconfig

  wp:
    build: .
    restart: "always"
    ports:
      - 8080:80
    volumes:
      - wp-data:/var/www/html:ro
      - ./wp-themes:/var/www/html/wp-content/themes:ro
      - ./wp-plugins:/var/www/html/wp-content/plugins:ro
      - ./wp-uploads:/var/www/html/wp-content/uploads
    depends_on:
      - wpconfig
      - wpcli
      - db
    links:
      - db

volumes:
  db-data:
  wp-data:
